### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by timbo82** [cflurin/homebridge-mqtt#10]
I get a connect error when trying to connect to my mqtt broker:

[10/26/2016, 12:32:19 PM] [mqtt] connect error! (url = mqtt://192.168.1.100:1883)

my config file is: 
       "platforms": [
                     {
                        "platform": "mqtt",
                        "name": "mqtt",
                        "url": "mqtt://192.168.1.100:1883"
                     }
                     ],
        "accessories": []

}

I have also tried excluding the port at the end. running this off a raspberry pi B+

apologies my firewall was blocking it. this can be cancelled

**Comment by cflurin** [comment]
Okay, closing

**Comment by mkormendy** [comment]
I'm getting the same thing. But I have no firewall blocking the requests as all traffic is on my internal network with no restrictions.
