### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by claudiuo** [cflurin/homebridge-mqtt#11]
Not an issue, just wanted to say thanks.

I just started playing with homekit and was wondering if there is a way to use node-red as the "backend". Till I saw your post just now on a homebridge issue I had no idea how this can be done. Thank you so much! Hopefully the notes on your homebridge-mqtt repo will help me move towards this very fast.

Thank you!

**Comment by cflurin** [comment]
Thanks for your feedback.
I'm glad that you can use homebridge-mqtt. Feel free to upload your use cases.

**Comment by danielsen2009** [comment]
Heres a fan controller I made. Only 2 speed so it uses <>50% for speed setting low/high.
https://www.youtube.com/watch?v=VV3ckHrjDhM
