### ISSUE TITLE
No Response Issue

### ISSUE THREAD

**Issue by maragelis** [cflurin/homebridge-mqtt#19]
Hi 

On my network i have to raspberry pi`s running Homebridge number one is running Mqtt and the other is running other platforms.

On the one running your mqtt i have an issue where suddenly after a few days all devices are not responding. I get a "No response" message on the devices. 
Checking the log file devices continue to be updated from mqtt and the Bridge running mqtt is responding in homekit. 

I think something is triggering  the no response but can not find what

**Comment by cflurin** [comment]
I'm also running homebridge-mqtt on a Rpi without any issue, take a look at:
https://github.com/cflurin/homebridge-punt/wiki/Running-Homebridge-on-a-Raspberry-Pi#troubleshooting
