### ISSUE TITLE
Handling of negative temperature values

### ISSUE THREAD

**Issue by Bjsulla** [cflurin/homebridge-mqtt#20]
Perhaps a beginners question but I have a problem with handling negative temperature values. Sending a command with the following payload works: {payload:{"name": "outdoor_temp", "characteristic": "CurrentTemperature", "value": "7"}}

But if I instead issue the command {payload:{"name": "outdoor_temp", "characteristic": "CurrentTemperature", "value": "-7"}} I get the following error: [mqtt] Accessory.parse outdoor_temp CurrentTemperature value '-7' outside range.

Is there any way to work around negative values?

**Comment by cflurin** [comment]
remove the accessory and add it again this way:
```sh
{
    "name":"outdoor_temp",
    "service":"TemperatureSensor",
    "CurrentTemperature": {
        "minValue": -20,
        "maxValue": 60,
        "minStep": 1
        }
    }
```

change `minValue`and `maxValue` for your need

**Comment by Bjsulla** [comment]
Worked great. Thank you!
