### ISSUE TITLE
Problem when homekit updates two or more identical characteristics on different accessories at the same time

### ISSUE THREAD

**Issue by grsir** [cflurin/homebridge-mqtt#21]
Environment:
- Setup 2 accessories that could set characteristics (ex: 2 Thermostat or 2 WindowCovering)
- If you are using Siri, you can control both accessories at once: "Hey Siri, set the temperature to 20°"

Symptom:
- Homebridge receive 1 request from HomeKit to set 2 characteristics on 2 different accessory:
```
  Accessory [HomeBridge] Processing characteristic set: [{"aid":50,"iid":10,"value":25},{"aid":51,"iid":10,"value":25}] +1ms
  Accessory [HomeBridge] Setting Characteristic "Target Position" to value 25 +0ms
  Accessory [HomeBridge] Setting Characteristic "Target Position" to value 25 +3ms
```
- Homebridge-mqtt handle only one of the 2 commands and after few seconds, Siri complains he didn't receive response from the system.

Cause:
- When a set command is received, a set_timeout is started (to avoid flooding?). If the same characteristic is set within the next 250ms, the first set_timeout is cancelled and a new one is started.

```
          if (set_timeout && c === pre_c) {
            console.log("clearing timeout...")
            clearTimeout(set_timeout);
          }
          set_timeout = setTimeout(function() {
            console.log("calling Mqtt.set...")
            Mqtt.set(this.name, c, value, callback);
          }.bind(this), 250);
          pre_c = c;

```

Fix/Workaround:
Never cancel the timeout or implement a per accessory timeout.

BTW, that code can also have strange results in some theoretical situation:
- one characteristic is updated, then another one, then the first one again within 250 ms...

**Comment by cflurin** [comment]
@grsir:
Thanks for your feedback, I hope to find time next week for this issue.
Otherwise Push requests are welcome.

**Comment by cflurin** [comment]
@grsir:

try the github version:

```sh
sudo npm install -g cflurin/homebridge-mqtt
```

**Comment by grsir** [comment]
@cflurin:

I just made few tests with your fix and everything seems perfect to me.

Thanks!
