### ISSUE TITLE
Identify Accessory

### ISSUE THREAD

**Issue by danielsen2009** [cflurin/homebridge-mqtt#23]
Am I missing this or does the identify accessory not get passed through?

**Comment by cflurin** [comment]
Correct, it's on my todo-list.
```js
Accessory.prototype.identify = function (paired, callback) {

  this.log("Accessory.identify %s", this.name);
  // todo
  callback();
}
```

**Comment by cflurin** [comment]
@danielsen2009 
the latest commit (version) supports Identify Accessory
```sh
sudo npm install -g cflurin/homebridge-mqtt
```

https://github.com/cflurin/homebridge-mqtt#identify-accessory

**Comment by danielsen2009** [comment]
Awesome! Thank you! Cant wait to get home and update.
