### ISSUE TITLE
Current Temperature en thermostat dont work

### ISSUE THREAD

**Issue by uronito** [cflurin/homebridge-mqtt#24]
Current Temperature en thermostat dont work

**Comment by danielsen2009** [comment]
I'm successfully using this for a thermostat. Can you share your sketch?

**Comment by uronito** [comment]
you 're right, was fail mine.

One question, when i connect thermostat with siri, automatically starts in auto mode.

Can i only start the thermostat without auto mode, for the thermostat starts in last mode in memory.

Thanks!!!!

**Comment by uronito** [comment]
how can add rotationspeed characteristic to thermostat service?

plugin ignore rotationspeed.

Thanks

**Comment by ssolmaz** [comment]
Which DIY mqtt thermostat project are you using?
I want to make one.

**Comment by cflurin** [comment]
@ssolmaz:
there are some examples for node-red and ESP8266:

https://flows.nodered.org/node/node-red-contrib-ramp-thermostat
https://github.com/danielsen2009/homebridge-mqtt-acessories

**Comment by ssolmaz** [comment]
Thank you @cflurin , i will try
if I can't succeed, I will ask for help again.
