### ISSUE TITLE
Thermostat: i can't set the current temperature :-(

### ISSUE THREAD

**Issue by dr-apple** [cflurin/homebridge-mqtt#28]
I have add a Thermostat and i can set the target Temp and the current Heatingstae, but it dosen't work to set the currentTemperature, it came not a erro message but the currentTemperature value is allways n.v. or 0.0°C 👎 

Can you please help my ?

**Comment by cflurin** [comment]
It should work.
Please post some more infos:
* homebridge-mqtt version?
* homekit app?
* your topic, payload for setting CurrentTemperature

**Comment by dr-apple** [comment]
homebridge-mqtt version: 3

homekit  app: eve

payload: {"name":"heizung", "characteristic":"CurrentTemperature","value":19.0}

**Comment by cflurin** [comment]
I suppose you mean version 0.3.0
v0.3.0 and higher supports multiple services therefore you need to define a service_name:

note: you might install the latest version 0.3.7from GitHub:

```sh
sudo npm install -g cflurin/homebridge-mqtt
```

1) remove your accessory
```sh
topic: homebridge/to/remove
payload: {"name": "heizung"}
```
2) add a new accessory:
```sh
topic: homebridge/to/add
payload: {"name": "heizung", "service_name": "temperature_control", "service": "Thermostat"}
```
3) set value:
```sh
topic: homebridge/to/set
payload: {"name": "heizung", "service_name": "temperature_control", "characteristic": "CurrentTemperature", "value": 19.0}
```

**Comment by dr-apple** [comment]
Thanks it works, but the problem was the eve app, with the app "device" works fine :-)
