### ISSUE TITLE
dimming a light....

### ISSUE THREAD

**Issue by dr-apple** [cflurin/homebridge-mqtt#31]
If I have a lamp, which is off, by siri dimme to 10%, is sent by mqtt following:

{"Name": "Living room light one", "service_name": "", "characteristic": "On", "value": true}

And immediately after that:

{"Name": "living room light one", "service_name": "", "characteristic": "Brightness", "value": 20}

Why is the first info sent that light is on?

Can one change the only dimm value comes?

**Comment by cflurin** [comment]
@dr-apple 
That's a HomeKit feature.
charachteristic "On" is set bei HomeKit whenever the Brightness changes from 0 for the first time.
Changing the Brightness e.g. from 20 to 40 will not send the characteristic "On".
