### ISSUE TITLE
Motion detection

### ISSUE THREAD

**Issue by sergejey** [cflurin/homebridge-mqtt#32]
Hello,

Could you please help me with payload for motion detection event?
I'm trying to send following to homebridge/to/set topic:
{"name":"MotionSensor1","service_name":"Motion 1","service":"MotionSensor","characteristic":"MotionDetected","value":true} 

but it does not work for some reason

**Comment by cflurin** [comment]
@sergejey It should work.

How did you add the accessory? this way?
```sh
topic: homebridge/to/add
payload: {"name":"MotionSensor1","service_name":"Motion 1","service":"MotionSensor"}
```

btw. you don't need the service vy `homebridge/to/set`:
```sh
{"name":"MotionSensor1","service_name":"Motion 1","characteristic":"MotionDetected","value":true}
```

**Comment by sergejey** [comment]
@cflurin , it works but it works strange for some reason -- it does not update the status on the phone in real-time (like it does for the switch for example). So I can set MotionDetected status but it takes a while when I got it updated on the phone. Did you see anything like that? Thanks anyway!

**Comment by cflurin** [comment]
Strange! It updates immediately on my iPhone.

Are you using a public mqtt-broker?
iOS device?
homebridge hardware, Raspberry PI?

My Layout:

- Homebridge on a RPi3
- mosquitto broker on a RPi2 in the same LAN
- EVE and Home app on an iPhone 6.
