### ISSUE TITLE
How to retain the status of accessory when restart Homebridge?

### ISSUE THREAD

**Issue by waritsan** [cflurin/homebridge-mqtt#35]
Hi,
When I restart Homebridge the value and status of accessories are reset. Is there a way to retain it? For example I set my thermostat TargetHeatingCoolingState to 2, but it changes back to 0 after restart. I'm using Mosquitto btw.

Thanks and appreciate you help,

**Comment by cflurin** [comment]
Try the latest version 0.4.3 from GitHub:
```sh
sudo install -g cflurin/homebridge-mqtt
```

**Comment by waritsan** [comment]
It works like a charm. Thank you so much @cflurin
