### ISSUE TITLE
[feature request] ack from device

### ISSUE THREAD

**Issue by fedor1210** [cflurin/homebridge-mqtt#38]
Hello.

Firstly, I want to thank you for this excellent plugin.

It would be perfect if there were optional some kind of requirement of “ack” from device that subscribed to homebridge/from/set. It is very important because user should know if the device isn’t responding.

Timeout -> device reachability state will be changed to “not available”.

When user acts with real HomeKit accessory, for example, taps the “Lamp” icon to turn it on, but it has somehow hung up, the spinning wheel appears, and after some time timeout and error happens, so user knows that there’s some problem with the Lamp accessory.

Now the spinning wheel (pending state) appears only for the time of publishing, and there’s no feedback except reachability status set by publishing it into topic homebridge/to/set/reachability.

Thank you in advance!

Sorry for my English.
–
Best wishes,
Fedor Zhuromsky

**Comment by cflurin** [comment]
Thanks for your feedback.
I'll have a look next week and see what I can do.

**Comment by tvillingett** [comment]
Maybe with some thought the "last will" in MQTT could be used to set the reachabiliy automatically when the agent loses connection with the broker.
