### ISSUE TITLE
What payload to send for camera configuration?

### ISSUE THREAD

**Issue by danielsen2009** [cflurin/homebridge-mqtt#4]
I've been playing around with the homebridge-camera-ffmpeg and have gotten a pi3 with the camera module working with this plugin. All the other accessories I have I added through homebridge-mqtt and I would prefer to just stick with it. Can you provide any clue as to what I need to pass to homebridge to set up a camera video/audio feed? It already streams in rtp/rtsp. I tried to pass the rtp stream url to the "supported configs" but just got invalid payload.

**Comment by cflurin** [comment]
Thanks for your feedback. I have to update homebridge-mqtt to the latest homebridge version. I'll be back next saturday and I'll try to add the camera support.

**Comment by cflurin** [comment]
I've just upload v0.2.0 to github.
This version supports the types as defined in:

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

Please install from github:
```
sudo npm install -g --unsafe-perm https://github.com/cflurin/homebridge-mqtt
```

However I'll get a pi camera next week and therefore I couldn't test the camera service yet.

**Comment by danielsen2009** [comment]
Great, thanks for the update!

**Comment by balsimpson** [comment]
Were you able to add a camera using this? What settings did you use? I am unable to change the stream size from 1280 to a lesser size. any help is appreciated.

**Comment by cflurin** [comment]
@balsimpson: I didn't use a camera yet. I'll will install a picamera as soon as possible.

**Comment by cflurin** [comment]
closing for now
