### ISSUE TITLE
Scene support

### ISSUE THREAD

**Issue by JonSilver** [cflurin/homebridge-mqtt#44]
It's been possible for a while to add third party scenes into HomeKit and have HomeKit activate them. For example Hue can do this. Would it be possible through homebridge-mqtt to send HomeKit named scenes which HomeKit then asks Homebridge-Mqtt to activate, so they get passed on to the back end?

**Comment by cflurin** [comment]
As far as I know homebridge doesn't support this feature and therefore the plugin cannot implement it. You might ask on the https://github.com/nfarina/homebridge repository to be sure.
