### ISSUE TITLE
Feature Request: Enable HomeKit accessory History

### ISSUE THREAD

**Issue by fahrvergnuugen** [cflurin/homebridge-mqtt#49]
Elgato Eve supports viewing HomeKit accessory device history (like temperature over time). I have a temperature/humidity accessory setup and am updating the values via MQTT. It would be great if we could also view the history of accessories created with the MQTT plugin. 

I'm not sure if other accessory types support history, but I could see it being useful for things like motion sensors.

See this plugin for an example: https://github.com/simont77/fakegato-history

And [here's a screenshot of what it looks like in Eve](https://files.slack.com/files-tmb/T07RU912T-F8C384VBJ-03526ada3a/image_uploaded_from_ios_720.png)

**Comment by cflurin** [comment]
@fahrvergnuugen 
 I'm working on other project just now but I'll have a look at your request as soon as possible.

**Comment by cflurin** [comment]
The history chart is a specific Elgato feature, the app Home doesn't support it.
I have no plan to add this feature for Elgato Eve, may be Apple will add ii to HomeKit in the future.
