### ISSUE TITLE
Elgato Eve Weather 

### ISSUE THREAD

**Issue by MarkusBe** [cflurin/homebridge-mqtt#50]
Is it possible to publish the temperature, humidity and pressure from an Elgato Eve Weather Sensor via MQTT? I have this nice little sensor and want to log the data of the sensor and make it available not only in the EVE-App (which is pretty nice) but also in some other applications, like my MagicMirror. Any Ideas of how to do that? 

Thank you!
Markus

**Comment by cflurin** [comment]
I don't think you can directly send data from the Elgato Eve Weather Sensor.
May be they have publish an API and you can connect the device e.g. to Node-RED?
