### ISSUE TITLE
receive all the connected devices

### ISSUE THREAD

**Issue by JensPauwels** [cflurin/homebridge-mqtt#53]
topic: homebridge/to/get
payload: {"name": "*"}

this will only work when your topic_type is on multiple. 

if my topic_type is on single i don't receive the data on the following topic: 'homebridge/from/response'

Any suggestions?

**Comment by cflurin** [comment]
Thanks for your feedback.

Try:
```sh
test/from/response/#
```

**Comment by cflurin** [comment]
Thanks for your feedback.

Try:
```sh
homebridge/from/response/#
```

**Comment by JensPauwels** [comment]
That fixed it! 👍
