### ISSUE TITLE
Error and where to go with the accessory

### ISSUE THREAD

**Issue by LJ-Mic** [cflurin/homebridge-mqtt#57]
**# 1**
I added homebridge-mqtt as usual.
When I start Homebridge, I get the following error message in the terminal:

> [2018-1-28 13:36:59] [mqtt] Connecting..
> _tls_common.js:88
>       c.context.setCert(options.cert);
>                 ^
> 
> Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
>     at Object.createSecureContext (_tls_common.js:88:17)
>     at Object.exports.connect (_tls_wrap.js:1047:48)
>     at Object.buildBuilder (/usr/local/lib/node_modules/homebridge-mqtt/node_modules/mqtt/lib/connect/tls.js:13:20)
>     at MqttClient.wrapper [as streamBuilder] (/usr/local/lib/node_modules/homebridge-mqtt/node_modules/mqtt/lib/connect/index.js:135:36)
>     at MqttClient._setupStream (/usr/local/lib/node_modules/homebridge-mqtt/node_modules/mqtt/lib/client.js:246:22)
>     at new MqttClient (/usr/local/lib/node_modules/homebridge-mqtt/node_modules/mqtt/lib/client.js:227:8)
>     at Object.connect (/usr/local/lib/node_modules/homebridge-mqtt/node_modules/mqtt/lib/connect/index.js:138:10)
>     at Model.start (/usr/local/lib/node_modules/homebridge-mqtt/lib/model.js:71:17)
>     at Controller.start (/usr/local/lib/node_modules/homebridge-mqtt/lib/controller.js:361:14)
>     at PluginPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-mqtt/index.js:69:23)
> 

I understand that it means that something is wrong with certain lines of code. I did not touch these.

**# 2**
I do not know if my english is so bad or there is no description. But I can not figure out what to do with the accessory code or where to insert it.
Is there a complete introduction somewhere?

**Comment by cflurin** [comment]
Hi,

Have a look here:
https://github.com/cflurin/homebridge-mqtt/wiki/How-to-report-issues

To ask for help:

https://slackin-znyruquwmv.now.sh/

Channel: `hombridge-mqtt`

**Comment by cflurin** [comment]
Closing for now.
