### ISSUE TITLE
Add FakeGatoHistoryService?

### ISSUE THREAD

**Issue by 01matrix01** [cflurin/homebridge-mqtt#58]
Hi, this is not not an issue, I really love this plugin, is really easy to add or remove items to my Homebridge configuration, but now I have found simont77 github repository with his:

https://github.com/simont77/homebridge-weather-station-extended

that is amazing with also support for graph on EVE app with his plugin:

https://github.com/simont77/fakegato-history

So my question is, it is possible to add fakegato-history and automatically add it on JSON post when I make a new Temp Sensor for example?

Thanks all.

**Comment by iChUdY** [comment]
It would be great 👌🏻

**Comment by kiran5k4u** [comment]
I am surprised this has not been addressed yet. Fakegato history is a very good for monitoring the history of sensors in eve app. If someone can throw some light how to include it through node-red then it would be great.
