### ISSUE TITLE
New HomeKit types?

### ISSUE THREAD

**Issue by ArnieX** [cflurin/homebridge-mqtt#6]
Hi,

will you add new HomeKit types https://developer.apple.com/reference/homekit/1627282-homekit_constants?

Thanks.

**Comment by cflurin** [comment]
Hi,
I'll be back tomorrow and let's see what I can do over the weekend.

**Comment by ArnieX** [comment]
@cflurin awesome! I'm looking forward ;)

**Comment by cflurin** [comment]
@ArnieX I've just upload v0.2.0 to github.
This version supports the types as defined in:

https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

Please install from github:
```
sudo npm install -g --unsafe-perm https://github.com/cflurin/homebridge-mqtt
```

**Comment by ArnieX** [comment]
@cflurin Great some of those that didn't work are working now.

But I have some issues with certain characteristics, for example battery status for sensors:

```javascript
Service.TemperatureSensor = function(displayName, subtype) {
Service.call(this, displayName, '0000008A-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.CurrentTemperature);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.StatusActive);
  this.addOptionalCharacteristic(Characteristic.StatusFault);
  this.addOptionalCharacteristic(Characteristic.StatusLowBattery);
  this.addOptionalCharacteristic(Characteristic.StatusTampered);
  this.addOptionalCharacteristic(Characteristic.Name);
};
```

Which I try to set like this:
```json
{"name": "Outdoor Temperature","characteristic": "StatusLowBattery","value": 1}
```

But it return error:
```json
{"ack":false,"message":"name 'Outdoor Temperature' characteristic do not match."}
```

**Comment by cflurin** [comment]
How did you add the accessory? did you define the optional characteristic?


topic: homebridge/to/add
payload:
```
  {
    "name": "Outdoor Temperature",
    "service": "TemperatureSensor",
    "StatusLowBattery": "default"
  }
```

**Comment by ArnieX** [comment]
No. I didn't know this has to be defined when created ;). I'll do that and come back to you.

**Comment by ArnieX** [comment]
@cflurin Yes it works this way. Thank you for clarification.
