### ISSUE TITLE
Problem with instances

### ISSUE THREAD

**Issue by NSCHI** [cflurin/homebridge-mqtt#63]
Hello,

I have a problem with this plugin. when I install it all instances cause an error only that mqqt is running. 

Apr 14 11:57:36 raspberrypi node[1450]: *** WARNING *** Please fix your application to use the native API of Avahi!
Apr 14 11:57:36 raspberrypi node[1450]: *** WARNING *** For more information see <http://0pointer.de/avahi-compa…node&f=DNSServiceRegister>
Apr 14 11:57:36 raspberrypi homebridge[1450]: *** WARNING *** Please fix your application to use the native API of Avahi!
Apr 14 11:57:36 raspberrypi homebridge[1450]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Apr 14 11:57:36 raspberrypi homebridge[1450]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Apr 14 11:57:36 raspberrypi homebridge[1450]: *** WARNING *** Please fix your application to use the native API of Avahi!
Apr 14 11:57:36 raspberrypi homebridge[1450]: *** WARNING *** For more information see <http://0pointer.de/avahi-compa…node&f=DNSServiceRegister>
Apr 14 11:57:41 raspberrypi homebridge[1456]: [2018-4-14 11:57:41] Loaded plugin: homebridge-broadlink-rm
Apr 14 11:57:41 raspberrypi homebridge[1443]: [2018-4-14 11:57:41] Loaded plugin: homebridge-broadlink-rm
Apr 14 11:57:41 raspberrypi homebridge[1456]: [2018-4-14 11:57:41] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
Apr 14 11:57:41 raspberrypi homebridge[1456]: [2018-4-14 11:57:41] ---
Apr 14 11:57:41 raspberrypi homebridge[1443]: [2018-4-14 11:57:41] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
Apr 14 11:57:41 raspberrypi homebridge[1455]: [2018-4-14 11:57:41] Loaded plugin: homebridge-broadlink-rm
Apr 14 11:57:41 raspberrypi homebridge[1443]: [2018-4-14 11:57:41] ---
Apr 14 11:57:41 raspberrypi homebridge[1455]: [2018-4-14 11:57:41] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
Apr 14 11:57:41 raspberrypi homebridge[1455]: [2018-4-14 11:57:41] ---
Apr 14 11:57:41 raspberrypi homebridge[1444]: [2018-4-14 11:57:41] Loaded plugin: homebridge-broadlink-rm
Apr 14 11:57:41 raspberrypi homebridge[1444]: [2018-4-14 11:57:41] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
Apr 14 11:57:41 raspberrypi homebridge[1444]: [2018-4-14 11:57:41] ---
Apr 14 11:57:41 raspberrypi homebridge[1445]: [2018-4-14 11:57:41] Loaded plugin: homebridge-broadlink-rm
Apr 14 11:57:41 raspberrypi homebridge[1445]: [2018-4-14 11:57:41] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
Apr 14 11:57:41 raspberrypi homebridge[1445]: [2018-4-14 11:57:41] ---
Apr 14 11:57:42 raspberrypi homebridge[1455]: [2018-4-14 11:57:42] Loaded plugin: homebridge-mqtt
Apr 14 11:57:42 raspberrypi homebridge[1455]: homebridge API version: 2.2
Apr 14 11:57:42 raspberrypi homebridge[1455]: [2018-4-14 11:57:42] Registering platform 'homebridge-mqtt.mqtt'
Apr 14 11:57:42 raspberrypi homebridge[1455]: [2018-4-14 11:57:42] ---
Apr 14 11:57:42 raspberrypi homebridge[1450]: [2018-4-14 11:57:42] Loaded plugin: homebridge-broadlink-rm
Apr 14 11:57:42 raspberrypi homebridge[1443]: [2018-4-14 11:57:42] Loaded plugin: homebridge-mqtt
Apr 14 11:57:42 raspberrypi homebridge[1443]: homebridge API version: 2.2
Apr 14 11:57:42 raspberrypi homebridge[1443]: [2018-4-14 11:57:42] Registering platform 'homebridge-mqtt.mqtt'
Apr 14 11:57:42 raspberrypi homebridge[1450]: [2018-4-14 11:57:42] Registering platform 'homebridge-broadlink-rm.BroadlinkRM'
Apr 14 11:57:42 raspberrypi homebridge[1450]: [2018-4-14 11:57:42] ---
Apr 14 11:57:42 raspberrypi homebridge[1443]: [2018-4-14 11:57:42] ---
Apr 14 11:57:43 raspberrypi homebridge[1444]: [2018-4-14 11:57:43] Loaded plugin: homebridge-mqtt
Apr 14 11:57:43 raspberrypi homebridge[1444]: homebridge API version: 2.2
Apr 14 11:57:43 raspberrypi homebridge[1444]: [2018-4-14 11:57:43] Registering platform 'homebridge-mqtt.mqtt'
Apr 14 11:57:43 raspberrypi homebridge[1444]: [2018-4-14 11:57:43] ---
Apr 14 11:57:43 raspberrypi homebridge[1456]: [2018-4-14 11:57:43] Loaded plugin: homebridge-mqtt
Apr 14 11:57:43 raspberrypi homebridge[1456]: homebridge API version: 2.2
Apr 14 11:57:43 raspberrypi homebridge[1456]: [2018-4-14 11:57:43] Registering platform 'homebridge-mqtt.mqtt'
Apr 14 11:57:43 raspberrypi homebridge[1456]: [2018-4-14 11:57:43] ---
Apr 14 11:57:43 raspberrypi homebridge[1445]: [2018-4-14 11:57:43] Loaded plugin: homebridge-mqtt
Apr 14 11:57:43 raspberrypi homebridge[1445]: homebridge API version: 2.2
Apr 14 11:57:43 raspberrypi homebridge[1445]: [2018-4-14 11:57:43] Registering platform 'homebridge-mqtt.mqtt'
Apr 14 11:57:43 raspberrypi homebridge[1445]: [2018-4-14 11:57:43] ---
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] Loaded plugin: homebridge-people
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] Registering platform 'homebridge-people.People'
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] Registering accessory 'homebridge-people.PeopleAccessory'
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] Registering accessory 'homebridge-people.PeopleAllAccessory'
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] ---
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] Loaded plugin: homebridge-people
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] Registering platform 'homebridge-people.People'
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] Registering accessory 'homebridge-people.PeopleAccessory'
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] Registering accessory 'homebridge-people.PeopleAllAccessory'
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] ---
Apr 14 11:57:44 raspberrypi homebridge[1450]: [2018-4-14 11:57:44] Loaded plugin: homebridge-mqtt
Apr 14 11:57:44 raspberrypi homebridge[1450]: homebridge API version: 2.2
Apr 14 11:57:44 raspberrypi homebridge[1450]: [2018-4-14 11:57:44] Registering platform 'homebridge-mqtt.mqtt'
Apr 14 11:57:44 raspberrypi homebridge[1450]: [2018-4-14 11:57:44] ---
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] Loaded plugin: homebridge-platform-maxcube
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Apr 14 11:57:44 raspberrypi homebridge[1443]: [2018-4-14 11:57:44] ---
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] Loaded plugin: homebridge-platform-maxcube
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Apr 14 11:57:44 raspberrypi homebridge[1455]: [2018-4-14 11:57:44] ---
Apr 14 11:57:44 raspberrypi homebridge[1444]: [2018-4-14 11:57:44] Loaded plugin: homebridge-people
Apr 14 11:57:44 raspberrypi homebridge[1444]: [2018-4-14 11:57:44] Registering platform 'homebridge-people.People'
Apr 14 11:57:44 raspberrypi homebridge[1444]: [2018-4-14 11:57:44] Registering accessory 'homebridge-people.PeopleAccessory'
Apr 14 11:57:44 raspberrypi homebridge[1444]: [2018-4-14 11:57:44] Registering accessory 'homebridge-people.PeopleAllAccessory'
Apr 14 11:57:44 raspberrypi homebridge[1444]: [2018-4-14 11:57:44] ---
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] Loaded plugin: homebridge-people
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] Registering platform 'homebridge-people.People'
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] Registering accessory 'homebridge-people.PeopleAccessory'
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] Registering accessory 'homebridge-people.PeopleAllAccessory'
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] ---
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] Loaded plugin: homebridge-people
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] Registering platform 'homebridge-people.People'
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] Registering accessory 'homebridge-people.PeopleAccessory'
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] Registering accessory 'homebridge-people.PeopleAllAccessory'
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] ---
Apr 14 11:57:45 raspberrypi homebridge[1444]: [2018-4-14 11:57:45] Loaded plugin: homebridge-platform-maxcube
Apr 14 11:57:45 raspberrypi homebridge[1444]: [2018-4-14 11:57:45] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Apr 14 11:57:45 raspberrypi homebridge[1444]: [2018-4-14 11:57:45] ---
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] Loaded plugin: homebridge-platform-maxcube
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Apr 14 11:57:45 raspberrypi homebridge[1445]: [2018-4-14 11:57:45] ---
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] Loaded plugin: homebridge-platform-maxcube
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Apr 14 11:57:45 raspberrypi homebridge[1456]: [2018-4-14 11:57:45] ---
Apr 14 11:57:45 raspberrypi homebridge[1443]: [2018-4-14 11:57:45] Loaded plugin: homebridge-synology-surveillance-homemode
Apr 14 11:57:45 raspberrypi homebridge[1443]: [2018-4-14 11:57:45] Registering accessory 'homebridge-synology-surveillance-homemode.SSHomeMode'
Apr 14 11:57:45 raspberrypi homebridge[1443]: [2018-4-14 11:57:45] ---
Apr 14 11:57:45 raspberrypi homebridge[1443]: [2018-4-14 11:57:45] Loaded plugin: homebridge-telegram
Apr 14 11:57:45 raspberrypi homebridge[1443]: [2018-4-14 11:57:45] Registering platform 'homebridge-telegram.Telegram'
Apr 14 11:57:45 raspberrypi homebridge[1443]: [2018-4-14 11:57:45] ---
Apr 14 11:57:45 raspberrypi homebridge[1455]: [2018-4-14 11:57:45] Loaded plugin: homebridge-synology-surveillance-homemode
Apr 14 11:57:45 raspberrypi homebridge[1455]: [2018-4-14 11:57:45] Registering accessory 'homebridge-synology-surveillance-homemode.SSHomeMode'
Apr 14 11:57:45 raspberrypi homebridge[1455]: [2018-4-14 11:57:45] ---
Apr 14 11:57:46 raspberrypi homebridge[1455]: [2018-4-14 11:57:46] Loaded plugin: homebridge-telegram
Apr 14 11:57:46 raspberrypi homebridge[1455]: [2018-4-14 11:57:46] Registering platform 'homebridge-telegram.Telegram'
Apr 14 11:57:46 raspberrypi homebridge[1455]: [2018-4-14 11:57:46] ---
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] Loaded plugin: homebridge-people
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] Registering platform 'homebridge-people.People'
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] Registering accessory 'homebridge-people.PeopleAccessory'
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] Registering accessory 'homebridge-people.PeopleAllAccessory'
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] ---
Apr 14 11:57:46 raspberrypi homebridge[1444]: [2018-4-14 11:57:46] Loaded plugin: homebridge-synology-surveillance-homemode
Apr 14 11:57:46 raspberrypi homebridge[1444]: [2018-4-14 11:57:46] Registering accessory 'homebridge-synology-surveillance-homemode.SSHomeMode'
Apr 14 11:57:46 raspberrypi homebridge[1444]: [2018-4-14 11:57:46] ---
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] Loaded plugin: homebridge-platform-maxcube
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] Registering platform 'homebridge-platform-maxcube.MaxCubePlatform'
Apr 14 11:57:46 raspberrypi homebridge[1450]: [2018-4-14 11:57:46] ---
Apr 14 11:57:46 raspberrypi homebridge[1444]: [2018-4-14 11:57:46] Loaded plugin: homebridge-telegram
Apr 14 11:57:46 raspberrypi homebridge[1444]: [2018-4-14 11:57:46] Registering platform 'homebridge-telegram.Telegram'
Apr 14 11:57:46 raspberrypi homebridge[1444]: [2018-4-14 11:57:46] ---
Apr 14 11:57:46 raspberrypi homebridge[1456]: [2018-4-14 11:57:46] Loaded plugin: homebridge-synology-surveillance-homemode
Apr 14 11:57:46 raspberrypi homebridge[1456]: [2018-4-14 11:57:46] Registering accessory 'homebridge-synology-surveillance-homemode.SSHomeMode'
Apr 14 11:57:46 raspberrypi homebridge[1456]: [2018-4-14 11:57:46] ---
Apr 14 11:57:46 raspberrypi homebridge[1456]: [2018-4-14 11:57:46] Loaded plugin: homebridge-telegram
Apr 14 11:57:46 raspberrypi homebridge[1456]: [2018-4-14 11:57:46] Registering platform 'homebridge-telegram.Telegram'
Apr 14 11:57:46 raspberrypi homebridge[1456]: [2018-4-14 11:57:46] ---
Apr 14 11:57:47 raspberrypi homebridge[1445]: [2018-4-14 11:57:47] Loaded plugin: homebridge-synology-surveillance-homemode
Apr 14 11:57:47 raspberrypi homebridge[1445]: [2018-4-14 11:57:47] Registering accessory 'homebridge-synology-surveillance-homemode.SSHomeMode'
Apr 14 11:57:47 raspberrypi homebridge[1445]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] Loaded plugin: homebridge-vorwerk
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] Registering platform 'homebridge-vorwerk.VorwerkVacuumRobot'
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] Loaded config.json with 0 accessories and 1 platforms.
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1445]: [2018-4-14 11:57:47] Loaded plugin: homebridge-telegram
Apr 14 11:57:47 raspberrypi homebridge[1445]: [2018-4-14 11:57:47] Registering platform 'homebridge-telegram.Telegram'
Apr 14 11:57:47 raspberrypi homebridge[1445]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] Loading 1 platforms...
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] [Telegram] Initializing Telegram platform...
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] [Telegram] TelegramPlatform Plugin Loaded
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] [Telegram] Found bot in config: "Haustelegram"
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] Loaded plugin: homebridge-vorwerk
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] Registering platform 'homebridge-vorwerk.VorwerkVacuumRobot'
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] Loaded config.json with 0 accessories and 1 platforms.
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] Loading 1 platforms...
Apr 14 11:57:47 raspberrypi homebridge[1450]: [2018-4-14 11:57:47] Loaded plugin: homebridge-synology-surveillance-homemode
Apr 14 11:57:47 raspberrypi homebridge[1450]: [2018-4-14 11:57:47] Registering accessory 'homebridge-synology-surveillance-homemode.SSHomeMode'
Apr 14 11:57:47 raspberrypi homebridge[1450]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [People] Initializing People platform...
Apr 14 11:57:47 raspberrypi homebridge[1450]: [2018-4-14 11:57:47] Loaded plugin: homebridge-telegram
Apr 14 11:57:47 raspberrypi homebridge[1450]: [2018-4-14 11:57:47] Registering platform 'homebridge-telegram.Telegram'
Apr 14 11:57:47 raspberrypi homebridge[1450]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [People] Initializing platform accessory 'Niko'...
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [People] Initializing platform accessory 'Christina'...
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [People] Initializing platform accessory 'Anyone'...
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [People] Initializing platform accessory 'No One'...
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [People] WebHook: Started server on port '51828'.
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] Loading 0 accessories...
Apr 14 11:57:47 raspberrypi homebridge[1443]: Load homebridge-mqtt.mqtt
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] config undefined or null!
Apr 14 11:57:47 raspberrypi homebridge[1443]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] storagePath = /var/homebridge-people
Apr 14 11:57:47 raspberrypi systemd[1]: homebridge-people.service: main process exited, code=exited, status=1/FAILURE
Apr 14 11:57:47 raspberrypi systemd[1]: Unit homebridge-people.service entered failed state.
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] [Telegram] Initializing platform accessory 'Haustelegram'...
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] Loading 0 accessories...
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] Loaded plugin: homebridge-vorwerk
Apr 14 11:57:47 raspberrypi homebridge[1455]: Load homebridge-mqtt.mqtt
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] Registering platform 'homebridge-vorwerk.VorwerkVacuumRobot'
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] config undefined or null!
Apr 14 11:57:47 raspberrypi homebridge[1455]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] storagePath = /var/homebridge-telegram
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] Loaded config.json with 0 accessories and 1 platforms.
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] Loading 1 platforms...
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [Broadlink] Initializing BroadlinkRM platform...
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [Broadlink] [INFO] Automatically discovering Broadlink RM devices.
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] Loaded plugin: homebridge-vorwerk
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] Registering platform 'homebridge-vorwerk.VorwerkVacuumRobot'
Apr 14 11:57:47 raspberrypi systemd[1]: homebridge-telegram.service: main process exited, code=exited, status=1/FAILURE
Apr 14 11:57:47 raspberrypi systemd[1]: Unit homebridge-telegram.service entered failed state.
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] Loaded config.json with 0 accessories and 1 platforms.
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] ---
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [Broadlink] [INFO] Running Homebridge Broadlink RM Plugin version 3.5.5
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] Loading 1 platforms...
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] [MaxCube Platform] Initializing MaxCubePlatform platform...
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [Broadlink] Rollladen Accessory Ready
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] [MaxCube Platform] Try connecting to Max! Cube..
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] Loading 0 accessories...
Apr 14 11:57:47 raspberrypi homebridge[1444]: Load homebridge-mqtt.mqtt
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] config undefined or null!
Apr 14 11:57:47 raspberrypi homebridge[1444]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] storagePath = /var/homebridge-max
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [Broadlink] Initializing platform accessory 'Learn'...
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [Broadlink] Initializing platform accessory 'Scan Frequency'...
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [Broadlink] Initializing platform accessory 'Rollladen'...
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] Loading 0 accessories...
Apr 14 11:57:47 raspberrypi homebridge[1456]: Load homebridge-mqtt.mqtt
Apr 14 11:57:47 raspberrypi systemd[1]: homebridge-max.service: main process exited, code=exited, status=1/FAILURE
Apr 14 11:57:47 raspberrypi systemd[1]: Unit homebridge-max.service entered failed state.
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] config undefined or null!
Apr 14 11:57:47 raspberrypi homebridge[1456]: [2018-4-14 11:57:47] [homebridge-mqtt.mqtt] storagePath = /var/homebridge-broadlink
Apr 14 11:57:47 raspberrypi systemd[1]: homebridge-broadlink.service: main process exited, code=exited, status=1/FAILURE
Apr 14 11:57:47 raspberrypi systemd[1]: Unit homebridge-broadlink.service entered failed state.
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] Loaded plugin: homebridge-vorwerk
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] Registering platform 'homebridge-vorwerk.VorwerkVacuumRobot'
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] ---
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] Loaded config.json with 1 accessories and 0 platforms.
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] ---
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] Loading 1 accessories...
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] [Security Cameras] Initializing SSHomeMode accessory...
Apr 14 11:57:48 raspberrypi homebridge[1445]: Load homebridge-mqtt.mqtt
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] [homebridge-mqtt.mqtt] config undefined or null!
Apr 14 11:57:48 raspberrypi homebridge[1445]: [2018-4-14 11:57:48] [homebridge-mqtt.mqtt] storagePath = /var/homebridge-security
Apr 14 11:57:48 raspberrypi systemd[1]: homebridge-security.service: main process exited, code=exited, status=1/FAILURE
Apr 14 11:57:48 raspberrypi systemd[1]: Unit homebridge-security.service entered failed state.
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] Loaded plugin: homebridge-vorwerk
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] Registering platform 'homebridge-vorwerk.VorwerkVacuumRobot'
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] ---
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] Loaded config.json with 0 accessories and 1 platforms.
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] ---
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] Loading 1 platforms...
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] [VorwerkVacuumRobot] Initializing VorwerkVacuumRobot platform...
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] Loading 0 accessories...
Apr 14 11:57:48 raspberrypi homebridge[1450]: Load homebridge-mqtt.mqtt
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] [homebridge-mqtt.mqtt] config undefined or null!
Apr 14 11:57:48 raspberrypi homebridge[1450]: [2018-4-14 11:57:48] [homebridge-mqtt.mqtt] storagePath = /var/homebridge-vorwerk
Apr 14 11:57:48 raspberrypi systemd[1]: homebridge-vorwerk.service: main process exited, code=exited, status=1/FAILURE
Apr 14 11:57:48 raspberrypi systemd[1]: Unit homebridge-vorwerk.service entered failed state.

can you fix this mistake?

**Comment by cflurin** [comment]
As in homebridge README explained:
**NOTE: Your config.json file MUST be inside of .homebridge, which is inside of your home folder.**

**Comment by NSCHI** [comment]
I have for each Plugin a instance s .service, now i can't operate .service with mqtt?

**Comment by cflurin** [comment]
I'm not sure what you are trying to do but have look here: https://github.com/cflurin/homebridge-mqtt/issues/8
Anyway please try to install homebridge-mqtt as explained in the doc.

**Comment by cflurin** [comment]
Homebridge-mqtt should now work with multiple instances. You can try the new version from gitHub:
```sh
sudo npm install -g --unsafe-perm cflurin/homebridge-mqtt
```
Have a look here: https://github.com/cflurin/homebridge-mqtt/issues/66

**Comment by cflurin** [comment]
Hi,
I didn't spend much time for the different autostart at boot options. I used `init.d` and now `systemd` (homebridge.service). It seems some users has an issues using systemd.

How are you running homebridge -P?

**Comment by bohtho** [comment]
@Maragelis It used to have a problem with multiple instances when not all were configed to use mqtt and the plugin was installed globally. Now that works fine as well as of version 0.5.0.

Regarding the “-P” argument: This means there’s a local node_modules for the instance and it searches for plugins here first. But will Config-X also respect this setting and install plugins locally (without “-g”)?
