### ISSUE TITLE
Can it be found when devices dropped？

### ISSUE THREAD

**Issue by linjiejim** [cflurin/homebridge-mqtt#65]
Not a issue but I want to figure out whether "Homebridge"could know when my devices is offline?
Something like "Heartbeat package" do, because I'm not sure if my device works still when I see everything right there in "HomeKit App" without any signs.

**Comment by cflurin** [comment]
Have a look here: 
https://github.com/cflurin/homebridge-mqtt#set-reachability
and
https://github.com/cflurin/homebridge-mqtt/issues/9
