### ISSUE TITLE
Plugin interfering with multiple instances of Homebridge

### ISSUE THREAD

**Issue by bohtho** [cflurin/homebridge-mqtt#66]
I have multiple instances of Homebridge where only one is configured to use homebridge-mqtt, but the mere existence (and loading) of the globally installed homebridge-mqtt plugin causes the second one to fail to start.

There's a simple fix to this bug proposed here (two possible solutions) if you agree and could implement:

https://github.com/oznu/homebridge-config-ui-x/issues/17#issuecomment-389465345

**Comment by cflurin** [comment]
Please post the log from homebridge start.
Probably you will see an error message:
`config undefined or null!`

**Comment by cflurin** [comment]
```js
    this.log.error("config undefined or null!");
    this.log("storagePath = %s", storagePath);
```
these logs show the error and the storagePath,
so I need the log of the instance using homebridge-mqtt.

**Comment by bohtho** [comment]
Sorry if I'm not following but the other (first) instance that *is* configured to use homebridge-mqtt logs this without error (even after my out-commenting in index.js):

> May 16 22:22:13 LillePi homebridge[28553]: [2018-5-16 22:22:13] Loaded plugin: homebridge-config-ui-x
> May 16 22:22:13 LillePi homebridge[28553]: [2018-5-16 22:22:13] Registering platform 'homebridge-config-ui-x.config'
> May 16 22:22:13 LillePi homebridge[28553]: [2018-5-16 22:22:13] ---
> May 16 22:22:13 LillePi homebridge[28553]: [2018-5-16 22:22:13] Plugin /usr/local/lib/node_modules/homebridge-hue requires Node version of ^8.11.1 which does not satisfy the current Node version of v9.9.0. You may need to upgrade your installation of Node.
> May 16 22:22:15 LillePi homebridge[28553]: [2018-5-16 22:22:15] Loaded plugin: homebridge-hue
> May 16 22:22:15 LillePi homebridge[28553]: [2018-5-16 22:22:15] Registering platform 'homebridge-hue.Hue'
> May 16 22:22:15 LillePi homebridge[28553]: [2018-5-16 22:22:15] ---
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] Loaded plugin: homebridge-mqtt
> May 16 22:22:16 LillePi homebridge[28553]: homebridge API version: 2.2
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] Registering platform 'homebridge-mqtt.mqtt'
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] ---
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] Loaded config.json with 0 accessories and 3 platforms.
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] ---
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] Loading 3 platforms...
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [Config] Initializing config platform...
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [Config] Spawning homebridge-config-ui-x with PID 28594
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [mqtt] Initializing mqtt platform...
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [mqtt] homebridge-mqtt v0.4.8
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [Hue] Initializing Hue platform...
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [Hue] homebridge-hue v0.9.2, node v9.9.0, homebridge v0.4.42
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [Hue] warning: not using recommended node version v8.11.1 LTS
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [Hue] warning: not using recommended homebridge version v0.4.38
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] Loading 0 accessories...
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [mqtt] Number of cached Accessories: 11
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [mqtt] clientId = homebridge-mqtt_05073749
> May 16 22:22:16 LillePi homebridge[28553]: [2018-5-16 22:22:16] [mqtt] Connecting..
> May 16 22:22:17 LillePi homebridge[28553]: [2018-5-16 22:22:17] [mqtt] connected (url = mqtt://127.0.0.1)

**Comment by cflurin** [comment]
Ok, it seems to be a multi-instance issue. Have a look here:
https://github.com/nfarina/homebridge/issues/1160

I have to investigate, but you can try to replace line 34 with `return;`
```js
-- process.exit(1);
++ return;
```

**Comment by bohtho** [comment]
Yep, that works! The second Homebridge instance now manages to start up (without homebridge-mqtt configured as a platform in its config.json). It just logs the following on this instance but continues:

> [2018-5-16 23:29:35] [homebridge-mqtt.mqtt] config undefined or null!
> [2018-5-16 23:29:35] [homebridge-mqtt.mqtt] storagePath = /var/lib/homebridge-ext

**Comment by cflurin** [comment]
I've uploaded a new version, please install from gitHub:
```sh
sudo npm install -g --unsafe-perm cflurin/homebridge-mqtt
```

**Comment by bohtho** [comment]
Awesome! Will you push it to npmjs as well?
