### ISSUE TITLE
No Message from MotionSensor

### ISSUE THREAD

**Issue by marcelkordek** [cflurin/homebridge-mqtt#68]
Hi,
if my MotionSensor triggers MotionDetected I don't receive a message on topic homebridge/from/set.
How can I fix this?

Thanks,
Marcel

**Comment by cflurin** [comment]
Please have a look here:
https://github.com/cflurin/homebridge-mqtt/wiki/How-to-report-issues

**Comment by marcelkordek** [comment]
Hi cflurin,
sorry here are the Details:

## **Versions**

- Homebridge: 0.4.42
- Node: 8.11.2
- Homebridge-MQTT: 0.5.0
- OS: Raspbian GNU/Linux 9 (stretch)

## **Config**

`{"name":"Doorbell","service":"MotionSensor"}`

## **Description**

After my Doorbell rings, it send a message to `homebridge/to/set -> {"name":"Doorbell","characteristic":"MotionDetected","value":true}` to trigger the MotionDetected in Homekit. Every time my Doorbell rings I receive a notification from Homekit with an Image from my IP-Camera (same 'room').

But I don't receive a message at `homebridge/from/set` when my Doorbell rings.

## **Log**
```
[2018-5-28 10:18:27] [mqtt] Number of cached Accessories: 7
[2018-5-28 10:18:27] [mqtt] clientId = homebridge-mqtt_*****
[2018-5-28 10:18:27] [mqtt] Connecting..
[2018-5-28 10:18:27] Homebridge is running on port *****.
[2018-5-28 10:18:27] [mqtt] connected (url = mqtt://**********)
```

Thanks,
Marcel

**Comment by cflurin** [comment]
I suppose the doorbell device sends the messages directly to homebridge-mqtt.
Where are you expecting `homebridge/from/set` ? in your doorbell device or e.g. node-red?

Anyway the `Characteristic.MotionDetected` has only a READ perm (no WRITE), therefore there is no set function.

```js
/**
 * Characteristic "Motion Detected"
 */

Characteristic.MotionDetected = function() {
  Characteristic.call(this, 'Motion Detected', '00000022-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.BOOL,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};
```

**Comment by marcelkordek** [comment]
That's correct my doorbell sends the message directly to homebridge-mqtt ->` homebridge/to/set`.
I'm expecting this in node-red to trigger other actions outside from HomeKit. 

For example:
- If I enter my HomeZone, set switch 'autoUnlock' for 10 Minutes to on (switch is added with homebridge-mqtt)
- If Doorbell rings, check if switch 'autoUnlock' is on
- If Doorbell rings and 'autoUnlock' is on, trigger the Doorlock (added with homebridge-mqtt) and set switch 'autoUnlock' to off

Ok, I understand. As a workaround I could have my Doorbell send two commands, one to ` homebridge/to/set` and the other one to another topic.

Thanks,
Marcel
