### ISSUE TITLE
possible to extract node from homebridge to node red?

### ISSUE THREAD

**Issue by MattL0** [cflurin/homebridge-mqtt#69]
Hi, 

i am not sure if this is able to do this... but i would like to extract node from homebridge  get the status and control them from node-red. I would then in the end add the node to my homeseer setup.

**Comment by cflurin** [comment]
I don't understand what you mean.
Please read the docs and give more details using the definitions for homebridge (HomeKit) like accessory, service, characteristic etc. and the same for node-red.

Have also a look here: https://github.com/cflurin/homebridge-mqtt/issues/8
