### ISSUE TITLE
homebridge-websocket or homebridge-mqtt?

### ISSUE THREAD

**Issue by protolyser** [cflurin/homebridge-mqtt#7]
Hi,
Sorry not really an issue but I don't know where to ask instead.
I'm new to Raspberry PI, homebridge and everything so I'm not really sure what plugin to use to realize my project.

Projet goal:
- Control RF sockets, Wifi Lights, Temperature sensors via Apple Home (Homebridge), and via Web UI (node-red), later Amazon Echo (Alexa).

What I did so far:
- Set up Raspberry PI 3 as a server in my home
-  install node-red and get my china no-name wifi led strip controller to work
- RF 433mhz sensor connected to the GPIOs with n8henrie/homebridge-rcswitch-gpiomem integrated in Apple Home / Siri

What I still want to do:
1: Control the RCSwitch stuff from node-red over a web surface
2. Controll the wifi led strips that I currently only control with node-red with Siri

What is the best of your plugins to use for that? 
How does it work? Do I setup all my devices and stuff in node-red and your plugins "automatically" add them to the homebridge config and make it visible for Apple Home?

Thanks for help, suggestions and tips :)

**Comment by cflurin** [comment]
Hi,
I'd suggest `homebridge-mqtt`. This is also the plugin I use for my smart-home based on node-red. Take a look at the README and the wiki.

**Comment by protolyser** [comment]
Ok, I looked in to it and like it a lot so far.
One problem I have is this:
I'm using node-red-dashboard for UI and node-red-contrib-rcswitch2 to control power sockets.
ui-switch [boolean true/false] --> rcswitch  ===> WORKS with the dashboard ui
Now when I want to use homebridge-mqtt I set the switch values to:
```
"When clicked, send:
On Payload: {"name":"Light","characteristic":"On","value": true}
Off Payload: {"name":"Light","characteristic":"On","value": false}
"
```
But then the rcswitch doesn't work anymore, it needs true and false as node input. (Switchvalue invalid found)

**Comment by protolyser** [comment]
![Uploading node-red-rcswitch.jpg…]()

**Comment by cflurin** [comment]
Hi,
There are some ways to simplify the flow.
Please export your flow and post a copy (text) to this threat.

**Comment by protolyser** [comment]
`[{"id":"13df6119.99a7b7","type":"rcswitch","z":"124675db.db19c2","name":"TV","func":0,"pin":0,"device":"A","group":"11000","channel":"","family":"","switchvalue":"2","systemcode":"","x":970,"y":160,"wires":[]},{"id":"30bebdaf.926be2","type":"rcswitch","z":"124675db.db19c2","name":"Soundsystem","func":0,"pin":0,"device":"B","group":"11000","channel":"","family":"","switchvalue":"2","systemcode":"","x":1000,"y":260,"wires":[]},{"id":"b2a2449a.c11db","type":"rcswitch","z":"124675db.db19c2","name":"Round Light","func":0,"pin":0,"device":"C","group":"11000","channel":"","family":"","switchvalue":"2","systemcode":"","x":990,"y":360,"wires":[]},{"id":"cac3cbbe.f3569","type":"rcswitch","z":"124675db.db19c2","name":"Light","func":0,"pin":0,"device":"D","group":"11000","channel":"","family":"","switchvalue":"2","systemcode":"","x":970,"y":480,"wires":[]},{"id":"1ec57d5b.9e0f83","type":"mqtt out","z":"124675db.db19c2","name":"","topic":"homebridge/to/set","qos":"","retain":"","broker":"8c053ce3.8adb98","x":1010,"y":60,"wires":[]},{"id":"1aceb4ed.8e9ae3","type":"mqtt in","z":"124675db.db19c2","name":"","topic":"homebridge/from/#","qos":"2","broker":"8c053ce3.8adb98","x":110,"y":80,"wires":[["d52c0113.27ef4","8448cba8.2001e"]]},{"id":"d52c0113.27ef4","type":"switch","z":"124675db.db19c2","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"{\"name\":\"Fernseher\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Fernseher\",\"characteristic\":\"On\",\"value\":false}","vt":"str"},{"t":"eq","v":"{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":false}","vt":"str"},{"t":"eq","v":"{\"name\":\"Kugel\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Kugel\",\"characteristic\":\"On\",\"value\":false}","vt":"str"},{"t":"eq","v":"{\"name\":\"Licht\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Licht\",\"characteristic\":\"On\",\"value\":false}","vt":"str"},{"t":"eq","v":"{\"name\":\"Studio Licht\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Studio Licht\",\"characteristic\":\"On\",\"value\":false}","vt":"str"}],"checkall":"true","outputs":10,"x":130,"y":360,"wires":[["2d95ffca.49f608"],["9f4f670c.ab312"],["4e6202ba.cfc554"],["2598f602.6231f2"],["34528d82.3322d2"],["10e53381.50ad54"],["53ba5ef1.2f93f8"],["a868c42f.895ed8"],[],[]]},{"id":"8448cba8.2001e","type":"debug","z":"124675db.db19c2","name":"","active":true,"console":"false","complete":"payload","x":370,"y":80,"wires":[]},{"id":"cd84ed83.4f12e","type":"ui_switch","z":"124675db.db19c2","name":"","label":"TV","group":"751bba10.476b9c","order":1,"width":0,"height":0,"passthru":false,"topic":"","style":"","onvalue":"{\"name\":\"Fernseher\",\"characteristic\":\"On\",\"value\":true}","onvalueType":"str","onicon":"","oncolor":"","offvalue":"{\"name\":\"Fernseher\",\"characteristic\":\"On\",\"value\":false}","offvalueType":"str","officon":"","offcolor":"","x":550,"y":160,"wires":[["1ec57d5b.9e0f83","b5cf5017.4d0ea8"]]},{"id":"ac7f97fb.bb0058","type":"ui_switch","z":"124675db.db19c2","name":"","label":"Soundsystem","group":"751bba10.476b9c","order":2,"width":0,"height":0,"passthru":false,"topic":"","style":"","onvalue":"{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":true}","onvalueType":"str","onicon":"","oncolor":"","offvalue":"{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":false}","offvalueType":"str","officon":"","offcolor":"","x":580,"y":260,"wires":[["1ec57d5b.9e0f83","bc2fb728.5e046"]]},{"id":"11000395.b6bf44","type":"ui_switch","z":"124675db.db19c2","name":"","label":"Round Light","group":"751bba10.476b9c","order":3,"width":0,"height":0,"passthru":false,"topic":"","style":"","onvalue":"{\"name\":\"Kugel\",\"characteristic\":\"On\",\"value\":true}","onvalueType":"str","onicon":"","oncolor":"","offvalue":"{\"name\":\"Kugel\",\"characteristic\":\"On\",\"value\":false}","offvalueType":"str","officon":"","offcolor":"","x":570,"y":360,"wires":[["1d71f372.2ee7a5","1ec57d5b.9e0f83"]]},{"id":"69880a37.eac60c","type":"ui_switch","z":"124675db.db19c2","name":"","label":"Light","group":"751bba10.476b9c","order":4,"width":0,"height":0,"passthru":false,"topic":"","style":"","onvalue":"{\"name\":\"Licht\",\"characteristic\":\"On\",\"value\":true}","onvalueType":"str","onicon":"","oncolor":"","offvalue":"{\"name\":\"Licht\",\"characteristic\":\"On\",\"value\":false}","offvalueType":"str","officon":"","offcolor":"","x":550,"y":480,"wires":[["d3730bf7.1b2a4","1ec57d5b.9e0f83"]]},{"id":"d3730bf7.1b2a4","type":"switch","z":"124675db.db19c2","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"{\"name\":\"Licht\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Licht\",\"characteristic\":\"On\",\"value\":false}","vt":"str"}],"checkall":"true","outputs":2,"x":690,"y":480,"wires":[["fe59327d.828d88"],["2ff9ef18.ebe35"]]},{"id":"fe59327d.828d88","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":830,"y":460,"wires":[["cac3cbbe.f3569"]]},{"id":"2ff9ef18.ebe35","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":830,"y":500,"wires":[["cac3cbbe.f3569"]]},{"id":"53ba5ef1.2f93f8","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":460,"wires":[["69880a37.eac60c","cac3cbbe.f3569"]]},{"id":"a868c42f.895ed8","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":500,"wires":[["69880a37.eac60c","cac3cbbe.f3569"]]},{"id":"2d95ffca.49f608","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":140,"wires":[["cd84ed83.4f12e","13df6119.99a7b7"]]},{"id":"9f4f670c.ab312","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":180,"wires":[["cd84ed83.4f12e","13df6119.99a7b7"]]},{"id":"4e6202ba.cfc554","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":240,"wires":[["ac7f97fb.bb0058","30bebdaf.926be2"]]},{"id":"2598f602.6231f2","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":280,"wires":[["ac7f97fb.bb0058","30bebdaf.926be2"]]},{"id":"34528d82.3322d2","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":340,"wires":[["11000395.b6bf44","b2a2449a.c11db"]]},{"id":"10e53381.50ad54","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":410,"y":380,"wires":[["11000395.b6bf44","b2a2449a.c11db"]]},{"id":"1d71f372.2ee7a5","type":"switch","z":"124675db.db19c2","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"{\"name\":\"Kugel\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Kugel\",\"characteristic\":\"On\",\"value\":false}","vt":"str"}],"checkall":"true","outputs":2,"x":730,"y":360,"wires":[["fca0033.42129"],["4eca5a38.87a2bc"]]},{"id":"4eca5a38.87a2bc","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":850,"y":380,"wires":[["b2a2449a.c11db"]]},{"id":"fca0033.42129","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":850,"y":340,"wires":[["b2a2449a.c11db"]]},{"id":"bc2fb728.5e046","type":"switch","z":"124675db.db19c2","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":false}","vt":"str"}],"checkall":"true","outputs":2,"x":730,"y":260,"wires":[["8655f5fa.ce9fa"],["c64b922e.872f48"]]},{"id":"c64b922e.872f48","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":850,"y":280,"wires":[["30bebdaf.926be2"]]},{"id":"8655f5fa.ce9fa","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":850,"y":240,"wires":[["30bebdaf.926be2"]]},{"id":"b5cf5017.4d0ea8","type":"switch","z":"124675db.db19c2","name":"","property":"payload","propertyType":"msg","rules":[{"t":"eq","v":"{\"name\":\"Fernseher\",\"characteristic\":\"On\",\"value\":true}","vt":"str"},{"t":"eq","v":"{\"name\":\"Fernseher\",\"characteristic\":\"On\",\"value\":false}","vt":"str"}],"checkall":"true","outputs":2,"x":730,"y":160,"wires":[["4c44ace5.ea3f8c"],["30abbf0c.01fa7"]]},{"id":"30abbf0c.01fa7","type":"function","z":"124675db.db19c2","name":"false","func":"msg.payload = false;\nreturn msg","outputs":1,"noerr":0,"x":850,"y":180,"wires":[["13df6119.99a7b7"]]},{"id":"4c44ace5.ea3f8c","type":"function","z":"124675db.db19c2","name":"true","func":"msg.payload = true;\nreturn msg","outputs":1,"noerr":0,"x":850,"y":140,"wires":[["13df6119.99a7b7"]]},{"id":"8c053ce3.8adb98","type":"mqtt-broker","z":"124675db.db19c2","broker":"127.0.0.1","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willPayload":"","birthTopic":"","birthQos":"0","birthPayload":""},{"id":"751bba10.476b9c","type":"ui_group","z":"124675db.db19c2","name":"Schlafzimmer","tab":"3ba7065e.885afa","disp":true,"width":"6"},{"id":"3ba7065e.885afa","type":"ui_tab","z":"124675db.db19c2","name":"Home","icon":"dashboard","order":1}]`

this is the flow.
I'm using
Raspberry Pi 3, Linux 4.4.21-v7+ arm LE
node v6.7.0
npm v3.10.8
node-RED v0.14.6

node-red-dashboard
node-red-contrib-rcswitch2

**Comment by cflurin** [comment]
You should try to use the built-in functions and use JSON (object) instead of string. Just to give an idea I modified the first two devices:

```
[{
	"id": "78df3d45.ccb3d4",
	"type": "mqtt in",
	"z": "76778fb.48bd47",
	"name": "",
	"topic": "homebridge/from/set",
	"qos": "2",
	"broker": "26437af4.fda776",
	"x": 140,
	"y": 120,
	"wires": [
		["49630a91.d00d24", "a653994c.e4bf48"]
	]
}, {
	"id": "49630a91.d00d24",
	"type": "debug",
	"z": "76778fb.48bd47",
	"name": "",
	"active": true,
	"console": "false",
	"complete": "payload",
	"x": 430,
	"y": 120,
	"wires": []
}, {
	"id": "e5169337.589b",
	"type": "switch",
	"z": "76778fb.48bd47",
	"name": "",
	"property": "payload.name",
	"propertyType": "msg",
	"rules": [{
		"t": "eq",
		"v": "Fernsehen",
		"vt": "str"
	}, {
		"t": "eq",
		"v": "Analge",
		"vt": "str"
	}],
	"checkall": "true",
	"outputs": 2,
	"x": 110,
	"y": 260,
	"wires": [
		["bbf3ebe7.fcef68"],
		["8bc9675e.4f9fe8"]
	]
}, {
	"id": "a653994c.e4bf48",
	"type": "json",
	"z": "76778fb.48bd47",
	"name": "",
	"x": 110,
	"y": 180,
	"wires": [
		["e5169337.589b"]
	]
}, {
	"id": "bbf3ebe7.fcef68",
	"type": "change",
	"z": "76778fb.48bd47",
	"name": "value",
	"rules": [{
		"t": "move",
		"p": "payload.value",
		"pt": "msg",
		"to": "payload",
		"tot": "msg"
	}],
	"action": "",
	"property": "",
	"from": "",
	"to": "",
	"reg": false,
	"x": 250,
	"y": 240,
	"wires": [
		["fa0bb80b.b6e448"]
	]
}, {
	"id": "fa0bb80b.b6e448",
	"type": "ui_switch",
	"z": "76778fb.48bd47",
	"name": "",
	"label": "TV",
	"group": "9669ad39.cae82",
	"order": 1,
	"width": 0,
	"height": 0,
	"passthru": true,
	"topic": "",
	"style": "",
	"onvalue": "true",
	"onvalueType": "bool",
	"onicon": "",
	"oncolor": "",
	"offvalue": "false",
	"offvalueType": "bool",
	"officon": "",
	"offcolor": "",
	"x": 370,
	"y": 240,
	"wires": [
		["21d28e4b.006802"]
	]
}, {
	"id": "8bc9675e.4f9fe8",
	"type": "change",
	"z": "76778fb.48bd47",
	"name": "value",
	"rules": [{
		"t": "move",
		"p": "payload.value",
		"pt": "msg",
		"to": "payload",
		"tot": "msg"
	}],
	"action": "",
	"property": "",
	"from": "",
	"to": "",
	"reg": false,
	"x": 250,
	"y": 280,
	"wires": [
		["1a3b2ca9.7ef793"]
	]
}, {
	"id": "1a3b2ca9.7ef793",
	"type": "ui_switch",
	"z": "76778fb.48bd47",
	"name": "",
	"label": "Soundsystem",
	"group": "9669ad39.cae82",
	"order": 2,
	"width": 0,
	"height": 0,
	"passthru": true,
	"topic": "",
	"style": "",
	"onvalue": "{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":true}",
	"onvalueType": "json",
	"onicon": "",
	"oncolor": "",
	"offvalue": "{\"name\":\"Anlage\",\"characteristic\":\"On\",\"value\":false}",
	"offvalueType": "json",
	"officon": "",
	"offcolor": "",
	"x": 400,
	"y": 280,
	"wires": [
		["21d28e4b.006802"]
	]
}, {
	"id": "21d28e4b.006802",
	"type": "debug",
	"z": "76778fb.48bd47",
	"name": "",
	"active": true,
	"console": "false",
	"complete": "false",
	"x": 590,
	"y": 260,
	"wires": []
}, {
	"id": "26437af4.fda776",
	"type": "mqtt-broker",
	"z": "76778fb.48bd47",
	"broker": "127.0.0.1",
	"port": "1883",
	"clientid": "",
	"usetls": false,
	"compatmode": true,
	"keepalive": "60",
	"cleansession": true,
	"willTopic": "",
	"willQos": "0",
	"willPayload": "",
	"birthTopic": "",
	"birthQos": "0",
	"birthPayload": ""
}, {
	"id": "9669ad39.cae82",
	"type": "ui_group",
	"z": "76778fb.48bd47",
	"name": "Schlafzimmer",
	"tab": "fdcb1e70.03d9e",
	"disp": true,
	"width": "6"
}, {
	"id": "fdcb1e70.03d9e",
	"type": "ui_tab",
	"z": "76778fb.48bd47",
	"name": "Home",
	"icon": "dashboard"
}]
```

**Comment by protolyser** [comment]
Thanks alot that makes it easier. 
The only problem is that when I change the switch on the node-red ui websurface it doesn't change the status in apple home because it only gets the boolean value. Any idea how to change that?

**Comment by cflurin** [comment]
Add a Template between ui-switch and mqtt-out, e.g.:
```
{"name":"Fernseher","characteristic":"On","value":{{payload}}}
``` 
BTW: you you can find more infos in the node-red google user group and on node-red slack.

https://groups.google.com/forum/#!forum/node-red
http://nodered.org/slack/

**Comment by protolyser** [comment]
awesome! that works perfectly, thanks a lot for the help

**Comment by protolyser** [comment]
I have another question: currently I only used the services "switch" and "lightbulb".
Now I have something that isn't a switch but only a button. There should be no on/off state, only a simple button that can be triggered.
Is there a service for that?

**Comment by cflurin** [comment]
HomeKit doesn't provide such a service as far as I know.
Take a look [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js)

**Comment by tvillingett** [comment]
There is a Service "Stateful Programmable Switch" and Service "Stateless Programmable Switch", I have never tried to use them though. I think it is the "button" function you want.
See: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

**Comment by protolyser** [comment]
Thanks I didn't see that. I tried to add a "button" with 
{"name":"Display aus","service":"StatelessProgrammableSwitch"}
I can see the button in Apple Home then, but it says "Unsupported Device" and doesn't function.

**Comment by tvillingett** [comment]
ok, I guess there is no "Made for iPhoen" real HW manufacturer that have this as a product yet?
