### ISSUE TITLE
Lightbulb service glitchy color picker

### ISSUE THREAD

**Issue by SebDominguez** [cflurin/homebridge-mqtt#71]
Hi,
I'm experimenting a strange problem.
If I setup a light with BOTH RGB+Temp setting, the color picker (where you can have 6 saved color, not the wheel) the input get ignored and the color isn't.

This is really difficult to explain so there is a screen recording showing the issue

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/6MvGvhb06Hs/0.jpg)](https://www.youtube.com/watch?v=6MvGvhb06Hs)

this is the configuration that I'm using

```json
{
    "name": "RGB and Temp Light",
    "service": "Lightbulb",
    "Brightness": "default",
    "Hue": "default",
    "ColorTemperature": "default",
    "Saturation": "default"
}
```

and If I set my light like that:

```json
{
    "name": "RGB Light",
    "service": "Lightbulb",
    "Brightness": "default",
    "Hue": "default",
    "Saturation": "default"
}
```

or even:

```json
{
    "name": "Temp Light",
    "service": "Lightbulb",
    "Brightness": "default",
    "ColorTemperature": "default",
    "Saturation": "default"
}
```

I don't have any problem...

**Comment by cflurin** [comment]
Hi,
Which homebridge , hap-nodejs, homebridge-mqtt versions have you installed?
Try homebridge with debug mode to see what is going on.

```
homebridge -D
```

or display the the messages from hombridge-mqtt:

```
homebridge/from/#
```

e.g.

```
{
	"name": "RGB and Temp Light",
	"service_name": "RGB and Temp Light",
	"characteristic": "ColorTemperature",
	"value": 496
}
```

**Comment by SebDominguez** [comment]
homebridge 0.4.45
homebridge-mqtt 0.5.1
Not sure how to check hap-nodes version

I'll try to see if I can capture something on the debug output

**Comment by SebDominguez** [comment]
It seems that RGB light shouldn't be configured with both hue/sat and ColorTemperature as the resulting HomeKit device end up being glitchy.

**Comment by cflurin** [comment]
I'm not sure I understand your issue, In your log the values are sent by homebridge-mqtt.
Actually you should be able to choice any optional characteristic.

```
/**
 * Service "Lightbulb"
 */

Service.Lightbulb = function(displayName, subtype) {
  Service.call(this, displayName, '00000043-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.On);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.Brightness);
  this.addOptionalCharacteristic(Characteristic.Hue);
  this.addOptionalCharacteristic(Characteristic.Saturation);
  this.addOptionalCharacteristic(Characteristic.Name);
  this.addOptionalCharacteristic(Characteristic.ColorTemperature); //Manual fix to add temperature
};
``` 

What are you doing when you get the values from homebridge-mqtt?
Which lightbulb device are you using?
If you do it in node-red, post you simplified flow here.

**Comment by SebDominguez** [comment]
I'm not doing anything with Mqtt actually, I'm just trying to demonstrate you with simple dummy lights that when we setup **both color and temp** features, the Home.app is acting wired (as shown in the recording) to fix this issue a light **must** be configured **only** with **color** nor **temp**.

In other words **color** and **temp** setting must be mutual exclusive. (According to my testing and experimenting with a lot of plugin / Homebridge implementation that apparently got this point wrong like home assistant and other Homebridge Plugin)

**Comment by cflurin** [comment]
I see! Did you try another HomeKit app like EVE?
Anyway, It doesn't seem to be an homebridge-mqtt issue.

Search on homebridge / hap-nodejs repositories.

**Comment by SebDominguez** [comment]
Didn't tried EVE. Now that I know how to avoid this glitch I'm sticking with Homebridge-mqtt.

Apparently Homeassistant developers don't consider this as a bug but a feature, so I'm just giving up on trying to make this glitchy software to works.

Since I'm not a Homebridge / hap-nodejs developers I don't have any clues on where to start to troubleshoot this problem.

Thanks you anyway for your plugin, it's the only Homebridge Plugin that have such flexibility that make  working color lights a possibility.

Updating the readme regarding this unusual Home.app behavior might be a good idea.

**Comment by nicoh88** [comment]
@SebDominguez-zz 

**Do you know if the problem has been solved?**

We have the same problem as soon as we configure `Characteristic.ColorTemperature` next to `Characteristic.Hue` and `Characteristic.Saturation`. But without `Characteristic.ColorTemperature` natural colors are not possible. 😢
