### ISSUE TITLE
[Support] Accessories vs Services

### ISSUE THREAD

**Issue by Jayphen** [cflurin/homebridge-mqtt#72]
Sorry to post this here, but I wasn't sure where else to ask for support.

I am new to Homebridge, and I am confused by the concept of "Accessories" vs "Services". Is this a concept that is unique to `homebridge-mqtt`? If not, could you please point me in the right direction to learn more about this topic?

Thanks

**Comment by cflurin** [comment]
> Is this a concept that is unique to `homebridge-mqtt`?

No, this is a Apple concept.

search for `HomeKit`
and have a look here:

https://github.com/nfarina/homebridge
https://github.com/KhaosT/HAP-NodeJS

**Comment by Jayphen** [comment]
Okay, thank you. It seems that https://github.com/KhaosT/HAP-NodeJS has the best explanation.
