### ISSUE TITLE
Where can I find documention of posible accessories and services?

### ISSUE THREAD

**Issue by osos** [cflurin/homebridge-mqtt#73]
This plugin is great.

However, I cannot seem to find a complete list of which accessories can be created, and in turn which services and characterisc such services have.

Any pointers?

**Comment by cflurin** [comment]
See README!

**HomeKitTypes.js describes all the predifined Services, Characteristcs, format and properties for the value e.g.:**

**Comment by osos** [comment]
Ok, had hoped for some classic documentation and not code review.

Thx anyway.

**Comment by bohtho** [comment]
Your question depends on your Homebridge version (and further your iOS and potentially tvOS version). This plugin only acts as a gateway of sorts to whatever accessories and services are available on the other end (or in the latest Homebridge) as far as I can tell.
