### ISSUE TITLE
refresh status and save function after reset

### ISSUE THREAD

**Issue by mickelk** [cflurin/homebridge-mqtt#74]
Hello!
I am just at the stage of installing window blinds from the guide https://maxmacstn.wordpress.com/2018/08/12/diy-ม่านไฟฟ้าจากม่าน-ikea/

I have two problems:
1. After adding the blind to MQTT LENS, it is displayed in HomeKIT but after resetting Homebridge removes it. What should I do to stay permanently?

<a href="https://ibb.co/Q96nVdw"><img src="https://i.ibb.co/p23ZTyF/Zrzut-ekranu-2019-03-23-o-00-50-30.png" alt="Zrzut-ekranu-2019-03-23-o-00-50-30" border="0"></a>

2. When opening the blind, when it is already 100% open in HomeKIT, I still have the status of opening ... and it does not change to OPEN

<a href="https://imgbb.com/"><img src="https://i.ibb.co/CHdBj8V/Zrzut-ekranu-2019-03-23-o-00-51-58.png" alt="Zrzut-ekranu-2019-03-23-o-00-51-58" border="0"></a>

**Comment by bakman2** [comment]
I spend some time figuring out how WindowCovering works:

You have to send in this order:
TargetPosition, CurrentPosition, PositionState. 

Then the icon will change its state.
To make it permanent you need to use the mqtt 'retain' flag.
