### ISSUE TITLE
Invalid JSON format 

### ISSUE THREAD

**Issue by sap-err** [cflurin/homebridge-mqtt#75]
Hi, I'm using temperature sensor. It works ok form Mqtt console. But when I send mqtt message from my driver automatically - I get an error:
Topic: /AGK_MQTTGate_2048703094/cmd/homebridge/to/set
payload: {"name": "Temperature (ID=A16096DB)", "service_name": "temperature", "characteristic": "CurrentTemperature", "value": "26.00"}
response topic: /AGK_MQTTGate_2048703094/cmd/homebridge/from/response
response message: {"ack":false,"message":"invalid JSON format"}

And again it works ok with the same data from console. Could you help me please?

**Comment by cflurin** [comment]
Hi,
It seems that your payload is invalid.
Use a tool like: https://github.com/thomasnordquist/MQTT-Explorer
and check what your driver is sending.

**Comment by sap-err** [comment]
Thanks a lot, found that there was an ending 0 in the package. Now it works. But I have one more question. Why is the name of added accessory is ignored in My home app? It seems that the service_name is displayed instead.
