### ISSUE TITLE
not possible to get accessories defined outside homebridge-mqtt

### ISSUE THREAD

**Issue by tvillingett** [cflurin/homebridge-mqtt#8]
Is it possible in any way to get hold of, and control, other accessories, like lamps etc, that was not configured in the scope of homebridge-mqtt, but exists on the same homebridge, or same Home?

**Comment by cflurin** [comment]
@tvillingett:
Short answer: no it isn't possible

There are 3 different layers:
1. Homekit with access to all accessories.
2. Homebridge has only access to all accessories defined in the installed plugins.
3. Plugin has access to the hown accessories.

The MQTTAPI could be added to layer 2 (homebridge), this depend on the homebridge-developers. I don't think Apple will be willing to add a MQTT API to Homekit.

**Comment by tvillingett** [comment]
I get it, not really feasible...

**Comment by timbru31** [comment]
I'm a bit late to the party, but a (very) inconvenient way is to use the hidden API of homebridge in the insecure mode. E.g. http://<your-ip>:51826/accessories

If someone is interested I can share my blueprint for toggling Hue lamps via a Sonoff T1 that sends a custom MQTT message

**Comment by timbru31** [comment]
You don't even need this plugin to expose the API. Just start homebridge with the -I flag. ;)
Correct, every device is exposed via the raw HomeKit protocol/API (HAP).

See e.g. https://github.com/nfarina/homebridge/issues/1219#issuecomment-288243015 and, https://github.com/oznu/hap-client or https://developer.apple.com//homekit/specification/ for more information about the HAP

**Comment by bohtho** [comment]
I see. Well, if in insecure mode, it would be great if 

`topic: homebridge/to/get
payload: {"name": "*"}`

would return every accessory in the homebridge instance.

**Comment by bohtho** [comment]
If any developers for the mqtt plugin would like inspiration, homebridge-config-x (Homebridge GUI plugin) does exactly this when Homebridge is run in insecure mode. Then a new tab is available with a graphical layout showing all accessories regardless of plugins, with states and the ability to manipulate them.

**Comment by bohtho** [comment]
Now the HAP-nodered node for Node-Red does this and works great along with homebridge-mqtt.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArnoldGoat** [comment]
I've just had a go with this: Home(iPadOS)->homebridge+websockets->homebrew program->wifi->flashed Sonoff->heater and it works. But if I want to extend this to lots of devices, it seems that there is just one global namespace. So I could have lounge-heater and office-heater, but I can't have 'heater' on its own within the scope of a room? Not sure how Siri could cope with all this. (Fwiw the homebrew program->wifi->flashed sonoff bit has been working for ages with a web browser control. The browser has a location hierarchy structure)

**Comment by ArnoldGoat** [comment]
Sorry - wrong place for post.
