### ISSUE TITLE
return Accessory Identify - serialnumber?

### ISSUE THREAD

**Issue by IoTPlay** [cflurin/homebridge-mqtt#84]
Hi, in readme.md under https://github.com/cflurin/homebridge-mqtt#identify-accessory you show below, but it is not clear how to get all that info back.
```
topic: homebridge/from/identify
payload: {"name":"indoor_temp","manufacturer":"homebridge-mqtt","model":"v0.3.0","serialnumber":"2017-02-13T12:17"}
```

Sending `{"name": "*" }` to `homebridge/to/get` does not return the `serialnumber` on `homebridge/from/#`?

**Comment by cflurin** [comment]
Hi,
It seems that this feature has been removed in the home app and EVE app.
Please ask on the homebridge repository:
https://github.com/nfarina/homebridge

**Comment by IoTPlay** [comment]
Thank you.
