### ISSUE TITLE
How to send multiple characteristics like "Active" & "inUse" for Valve to homebridge/to/set ?

### ISSUE THREAD

**Issue by IoTPlay** [cflurin/homebridge-mqtt#85]
Hi, for instance, the service `Valve` has 3 x required characteristics: Active, ValveType, and inUse. I got Active to work, but how can I send Active, and inUse in one message?

```
{"name":"ESP62.Switch.Relay1","service_name":"Sprinkler Leg-1","characteristic":"Active","value":"1"}
```

**Comment by IoTPlay** [comment]
This fails to send to mqtt hombridge/to/set :

```
{"name":"ESP62.Switch.Relay1","service_name":"Sprinkler Leg-1","characteristic":"inUse","value":"1"}
```

**Comment by cflurin** [comment]
> but how can I send Active, and inUse in one message?

You have to send a message for every characteristic.

> This fails to send to mqtt homebridge/to/set :

Depending on the characteristic you have to use the corresponding format.

`format: Formats.UINT8,`

```
{"name":"ESP62.Switch.Relay1","service_name":"Sprinkler Leg-1","characteristic":"inUse","value":1}
```
See:

https://github.com/KhaosT/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts

**Comment by cflurin** [comment]
Also replace `inUse` by `InUse`.

**Comment by IoTPlay** [comment]
Excellent, all working now, thanks.
