### ISSUE TITLE
Reachability

### ISSUE THREAD

**Issue by cflurin** [cflurin/homebridge-mqtt#9]
I've added `homebridge/to/set/reachability`

``` sh
topic: homebridge/to/set/reachability
payload: {"name": "flex_lamp", "reachable": true}
or
payload: {"name": "flex_lamp", "reachable": false}
```

Please install from GitHub:

``` sh
sudo npm install -g cflurin/homebridge-mqtt
```

**Comment by cflurin** [comment]
It seems that the Apple home app doesn't support this feature.
I've test it with EVE and here works.

**Comment by ArnieX** [comment]
@cflurin indeed Home.app doesn't support it. Then it is even more strange behaviour while Philips Hue is able to set "No response" status in Home.app the reachability characteristic does not. Any ideas? I have also come by reachability characteristic in Apple's datasheet for HomeKit but even thought I tried it before somehow it didn't work so I thought I'm doing something wrong and gave up. I have no idea what else it could be as Apple's datasheet doesn't quite give a lot info.

**Comment by cflurin** [comment]
@ArnieX:

Please install the latest version from GitHub.
It should now work for Home too (No Response)

**Comment by ArnieX** [comment]
You are officially my HERO! ;)

![](https://lh3.googleusercontent.com/cN4AALvMSreeLKacC8jjfI1_U5QQbhn_F_TYNa7Yk0J5MrX_0fq74_T5P-0TJiuMNLcID5IV6JVbRnOL528k-VR8z8AE6SzPPTeIf1ZEpG5Nz-zP1FQf1pnLfm9wNk90HfseGzOpdZMNmZUf2oyWR6nLulcZbAbhIVcRgxQYY6H2xSjbpW65rmCEeu-mfW2TY9YaXpsnN7j8lDVaSw8nAE9bjpeMmGtACDmV16KDwHyOoZvD2EOllwj-lkZIToJMItNcOzTwBdF8pu7ApsYKHS6aLTK-ywpxaEiOcnVFgK9kOO4_hI_dzqZKwQAxiooLjxMuqh7z-X2CS68j_hjH-HlaZwE67GYHhDbTa2aGlXhJtru0-UTpbfBXp2RXNu3X98i08s0m3tEdPqHTrxCwof4y1pfD7VLDpP_Esae9OJ7NmSOMpQZ_lDecct_sEdzyuJpcd0mKAccf45fTfULq_z8Xgde7kvf_l3zDErvwvcP3hy7N-eBHyxt1exS_qx8M6T0WOABVbobse1XqjI8Nrt_c_GPF95kqoRNhHubY-KsAn8ozjqgfOYON11slFutkDiJypl0f4QvmGT07_w1WcUfXWEEl4loDdY1b0pfvdLmWdvpUOA=w608-h1078-no)

Now I will just periodically test if device is connected or not.

**Comment by cflurin** [comment]
great! thanks for your feedback.

**Comment by tvillingett** [comment]
@ArnieX maybe you can use a "last Will and Testament" if your mqtt client supports that, which can helps to see if it is unreachable. Instead of writing extra client code. See example of use:
http://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testamenthttp://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament

**Comment by ArnieX** [comment]
@tvillingett that is a good idea and less overkill than pinging the device every 60second. Just please if it is possible to edit comment correct the URL you are referencing for future readers.

**Comment by CaptiveCreeper** [comment]
how do I make it so that the reachability is false when the device is not connected (off or not on the network).

**Comment by cflurin** [comment]
@CaptiveCreeper Have a look at the documentation https://github.com/cflurin/homebridge-mqtt#set-reachability

**Comment by CaptiveCreeper** [comment]
The documentation only shows how to set the reachability. It doesnt say anything about how to make it so that when the device no longer responds that it will show as not reachable

**Comment by tvillingett** [comment]
@CaptiveCreeper Is the idea to use "last will" that I wrote about above not working for you?

**Comment by CaptiveCreeper** [comment]
@tvillingett When I was looking into last will at first I apparently skimmed though it too much and misunderstood how it worked. After you responded saying that it should work I looked into it more and now it does work. Sorry for wasting your time with something that was already solved.

**Comment by ArnieX** [comment]
@tvillingett I have also used it on your tip, thanks for that.

**Comment by linjiejim** [comment]
Thanks for your reference @cflurin , and your tips @ArnieX @tvillingett 
Could you tell me how to set the accessory "NO RESPONSE", by using"homebridge/to/set/reachability" at server side? thank you in advance!
However, @tvillingett 's idea can be used on specific Topic, but "HB-mqtt APIs" are general topics, so it seems that the "last will testament" feature doesn't work fine with it? I will be grateful if you correct my mistake.

**Comment by linjiejim** [comment]
Cool! And thank you guys for your inspirations.
Finally I find it out and here is a brief for those who may need:
1.[mqtt client] publish a "LWT" to broker when connect with [topic] "homebridge/to/set/reachability "
 and [payload] "name": "YOUR_CLIENT_NAME", "reachable": false).
2.homebridge-mqtt will subscribe this topic and set to "unreachable" once client was ungracefully dropped.
3.remember to set reachability to true when CLIENT starts so that you can wake it up again.
