### ISSUE TITLE
validValues for a characteristic

### ISSUE THREAD

**Issue by faxioman** [cflurin/homebridge-mqtt#90]
Is there a way to set the "validValues" prop of a characteristic (eg. CurrentHeatingCoolingState of a thermostat than can only work in "heat" mode)?

**Comment by faxioman** [comment]
Ehm ... of course.

```
{
    "name": "My thermostat",
    "service_name": "thermostat",
    "service": "Thermostat",
    "TargetHeatingCoolingState": {
        "validValues": [
            0,
            1
        ]
    }
}
```

;)

**Comment by bohtho** [comment]
Can this be updated after the accessory is first created?
