### ISSUE TITLE
Topic: homebridge/to/add does not work for characteristics

### ISSUE THREAD

**Issue by LaborEtArs** [cflurin/homebridge-mqtt#98]
Is it possible, that there is no code for adding characteristics in the logic for 'homebridge/to/add'? At least publishing the topic to add one of the optional characteristics only leads to a '"message" : "name 'xyz' is already used."' response. In addition, I couldn't locate any code for adding characteristics...
If there in fact isn't existing code for adding characateristics, I would propose to add in to a new topic 'homebridge/to/addcharacteristic'.

**Comment by cflurin** [comment]
See: https://github.com/cflurin/homebridge-mqtt/issues/2

I'd appreciate a PR.

Topic:

```
hombebridge/to/add/charachteristic
```
