### ISSUE TITLE
How to install on Hassio / Home Assistant?

### ISSUE THREAD

**Issue by DIYtechie** [cflurin/homebridge-mqtt#99]
I’ve been using this great Mqtt-plugin on Raspbian with Node-RED for about a year, and this is simply the best. 

But now that I migrated to Home Assistant, how do I install it? I want to use it with Node-RED again.

**Comment by cflurin** [comment]
Hi,
I don't use Home Assistant but homebridge/homebridge-mqtt is standalone app and you should be able to exchange data over the mqtt-broker.

**Comment by PiRune** [comment]
@cflurin Sorry, should have been more clear. I’m no longer using Raspbian, but Home Assistant (previously called Hass.io). I know how to use the mqtt broker but not how to install the Homebridge-mqtt plug-in from Home Assistant.

**Comment by cflurin** [comment]
Sorry as I said I don't use Home Assistant. Are you able to install homebridge on Home Assistant?
